### ISSUE TITLE
"npm install" using (node > 7.0.0) results in error.

### ISSUE THREAD

**Issue by wmarshall484** [pcottle/learnGitBranching#466]
OSX Sierra: `10.12.6`
node: `v10.1.0`
npm: `6.0.1`

In the project's root directory after cloning, `npm install` results in:
```
wills-mbp:learnGitBranching wcmarsha$ npm install

> contextify@0.1.6 install /Users/wcmarsha/git/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:12:27: error: expected class name
class ContextifyContext : ObjectWrap {
                          ^
../src/contextify.cc:94:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/wcmarsha/.node-gyp/10.1.0/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/contextify.cc:109:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Run(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/wcmarsha/.node-gyp/10.1.0/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/contextify.cc:146:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> GetGlobal(const Arguments& args) {
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/wcmarsha/.node-gyp/10.1.0/include/node/v8.h:142:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/contextify.cc:167:54: error: unknown type name 'AccessorInfo'
                                               const AccessorInfo &accessInfo) {
                                                     ^
../src/contextify.cc:180:54: error: unknown type name 'AccessorInfo'
                                               const AccessorInfo &accessInfo) {
                                                     ^
../src/contextify.cc:189:54: error: unknown type name 'AccessorInfo'
                                               const AccessorInfo &accessInfo) {
                                                     ^
../src/contextify.cc:201:56: error: unknown type name 'AccessorInfo'
                                                 const AccessorInfo &accessInfo) {
                                                       ^
../src/contextify.cc:212:57: error: unknown type name 'AccessorInfo'
    static Handle<Array> GlobalPropertyEnumerator(const AccessorInfo &accessInfo) {
                                                        ^
../src/contextify.cc:21:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/wcmarsha/.node-gyp/10.1.0/include/node/v8.h:881:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/contextify.cc:22:39: error: 'New' is a private member of 'v8::PersistentBase<v8::Object>'
        sandbox = Persistent<Object>::New(sbox);
                                      ^
/Users/wcmarsha/.node-gyp/10.1.0/include/node/v8.h:630:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/contextify.cc:22:19: error: too few arguments to function call, expected 2, have 1; did you mean '::ContextifyContext::New'?
        sandbox = Persistent<Object>::New(sbox);
                  ^~~~~~~~~~
                  ::ContextifyContext::New
../src/contextify.cc:94:26: note: '::ContextifyContext::New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/contextify.cc:26:17: error: no member named 'Dispose' in 'v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >'
        context.Dispose();
        ~~~~~~~ ^
../src/contextify.cc:27:17: error: no member named 'Clear' in 'v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >'
        context.Clear();
        ~~~~~~~ ^
../src/contextify.cc:28:21: error: no member named 'Dispose' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
        proxyGlobal.Dispose();
        ~~~~~~~~~~~ ^
../src/contextify.cc:29:21: error: no member named 'Clear' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
        proxyGlobal.Clear();
        ~~~~~~~~~~~ ^
../src/contextify.cc:30:17: error: no member named 'Dispose' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
        sandbox.Dispose();
        ~~~~~~~ ^
../src/contextify.cc:31:17: error: no member named 'Clear' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
        sandbox.Clear();
        ~~~~~~~ ^
../src/contextify.cc:39:9: error: use of undeclared identifier 'ObjectWrap'
        ObjectWrap::Wrap(handle);
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wcmarsha/git/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.6 (node_modules/jquery/node_modules/jsdom/node_modules/contextify):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 5.013s
[!] 62 vulnerabilities found [8322 packages audited]
    Severity: 21 Low | 11 Moderate | 27 High | 3 Critical
    Run `npm audit` for more detail

```

**Comment by wmarshall484** [comment]
Seems to happen when installing `node-gyp`. The issue is documented here: https://github.com/brianmcd/contextify/issues/205

**Comment by pcottle** [comment]
great, lets track in that issue since it seems to be pretty deep in the dependencies.

but man, `jquery` -> `jsdom` -> `contextify`? would think installing jquery is straightforward
